services:
  bluemap:
    image: ghcr.io/bluemap-minecraft/bluemap:latest
    restart: "no"
    command: -r
    environment:
      - TZ=America/Toronto
    volumes:
      - '${HOST_PROJECT_DIR:-.}/config:/app/config'
      - '${HOST_PROJECT_DIR:-.}/config/webserver-off.conf:/app/config/webserver.conf'
      - '${WORLD_PATH:-./mc-data/world}:/app/world'
      - '${HOST_PROJECT_DIR:-.}/data:/app/data'
      - '${HOST_PROJECT_DIR:-.}/web:/app/web'
      - '${HOST_PROJECT_DIR:-.}/world_nether:/app/world_nether'
      - '${HOST_PROJECT_DIR:-.}/world_the_end:/app/world_the_end'
